version: 2

models:
    - name: karts_with_chassis_praga
      description: "Self descriptive"
      columns:
          - name: chassis
            description: "Chassis brand"
          - name: engine

    - name: uno
      description: "Just a dummy table"
      columns:
            - name: id
              description: "The primary key for this table"

sources:
  - name: public
    tables:
      - name: karts
        columns:
            - name: engine
              description: Engine of the kart
            - name: chassis
              description: Chassis of the kart
